/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#ifdef __ANDROID__
#include <TurboModule.h>
#elif __APPLE__
#include <ReactCommon/TurboModule.h>
#endif

namespace facebook
{
  namespace react
  {
    class JSI_EXPORT SchemaCxxSpecJSI : public TurboModule
    {
    protected:
      SchemaCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

    public:
      virtual jsi::Value setResponseParamsHandler(
          jsi::Runtime &rt,
          const jsi::Value &responseHandler) = 0;

      virtual jsi::Value createContext(
          jsi::Runtime &rt,
          const jsi::Value &configJson,
          const jsi::Value &onResult) = 0;

      virtual jsi::Value destroyContext(
          jsi::Runtime &rt,
          const jsi::Value &context) = 0;

      virtual jsi::Value sendRequestParams(
          jsi::Runtime &rt,
          const jsi::Value &context,
          const jsi::Value &requestId,
          const jsi::Value &functionName,
          const jsi::Value &functionParams) = 0;
    };

  } // namespace react
} // namespace facebook
