
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#include "NativeModules.h"

namespace facebook
{
  namespace react
  {
    static jsi::Value __hostFunction_SchemaCxxSpecJSI_setResponseHandler(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value *args, size_t count)
    {
      const jsi::Function responseHandler = args[0].asObject(rt).asFunction(rt);

      return static_cast<SchemaCxxSpecJSI *>(&turboModule)->setResponseHandler(rt, responseHandler);
    }

    static jsi::Value __hostFunction_SchemaCxxSpecJSI_createContext(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value *args, size_t count)
    {
      const jsi::String configJson = args[0].asString(rt);
      const jsi::Function onResult = args[1].asObject(rt).asFunction(rt);

      return static_cast<SchemaCxxSpecJSI *>(&turboModule)->createContext(rt, configJson, onResult);
    }

    static jsi::Value __hostFunction_SchemaCxxSpecJSI_destroyContext(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value *args, size_t count)
    {
      const jsi::Value context = args[0].asNumber();

      return static_cast<SchemaCxxSpecJSI *>(&turboModule)->destroyContext(rt, context);
    }

    static jsi::Value __hostFunction_SchemaCxxSpecJSI_sendRequest(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value *args, size_t count)
    {
      const jsi::Value context = args[0].asNumber();
      const jsi::Value requestId = args[1].asNumber();
      const jsi::String functionName = args[2].asString(rt);
      const jsi::String functionParamsJson = args[3].asString(rt);

      return static_cast<SchemaCxxSpecJSI *>(&turboModule)->sendRequest(rt, context, requestId, functionName, functionParamsJson);
    }

    SchemaCxxSpecJSI::SchemaCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
        : TurboModule("TrimTurboModule", jsInvoker)
    {
      methodMap_["setResponseHandler"] = MethodMetadata{1, __hostFunction_SchemaCxxSpecJSI_setResponseHandler};
      methodMap_["createContext"] = MethodMetadata{2, __hostFunction_SchemaCxxSpecJSI_createContext};
      methodMap_["destroyContext"] = MethodMetadata{1, __hostFunction_SchemaCxxSpecJSI_destroyContext};
      methodMap_["sendRequest"] = MethodMetadata{4, __hostFunction_SchemaCxxSpecJSI_sendRequest};
    }

  } // namespace react
} // namespace facebook
